### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by skyonedot** [sturdyfi/sturdy-airdrop-sybil#8] opened 2023-01-07 00:20 UTC
---
name: Sybil Attacker Report
about: Report a Sybil attacker of Sturdy
title: Sybil Attacker Report
labels: Sybil Report
assignees: 'skyone'

---

# Related Addresses

```
0xabc67a49d7d75bd04fa1dae22cd4b8c4f796540a
0xdaaa47da50c945bc97602cafe755cc2520ef2767
0x7a4c8e3655d665f3e25ccd6b60b1b024629b3705
```

# Reasoning

These three addresses have many internal ETH transfers, back and forth, and the amounts are relatively small

such as  

https://etherscan.io/tx/0x5939134beeafc9488ceeffc41f68252445a4dd41b73b0fb30d45a9df60ee3425 0xab-->0xda 0.01E

https://etherscan.io/tx/0x63bbcfb686229871b02e16b992fd18c9c18af80a2980ca6d8d9d5d5aa34bba0a 0xda-->0xab 0.02E

https://etherscan.io/tx/0x8332698a668d708350c909d5a8ee06ab32daba68f51a4b058c9f17745ca9f289 0x7a-->0xab 0.03E

https://etherscan.io/tx/0xdb29906efd336f19cb58b33fdf157285e775ee152ce90dd8ed0681e8d6646f6f 0xda-->0x7a 0.05E

https://etherscan.io/tx/0xfc14e33fe1b91fa33963a4f0e1110639eeba8c4acf12f40f74e71f00fa3fd5f5 0xab-->0x7a 0.001E

https://etherscan.io/tx/0x24057f5e86b03a4669b7048a33f4d3d7507a23f50cea203ae42a77637e3812d9 0x7a-->0xda 0.04E

# Methodology

I just gave a few examples of txs, but there are many more. Due to the following reasons:

1. Internal transfers, back and forth
2. Very small amounts, all less than 0.1 ETH

it is very suspicious.

# Rewards Address

0x8a09fb23e1c8d0ff9c9fef0bcfc9b9e07b1f0667

**Comment by sforman2000** [comment] 2023-01-08 05:34
Duplicate of https://github.com/sturdyfi/sturdy-airdrop-sybil/issues/1

**Closed as completed by sforman2000** 2023-01-08 05:34 UTC
