### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by skyonedot** [sturdyfi/sturdy-airdrop-sybil#7] opened 2023-01-07 00:04 UTC
---
name: Sybil Attacker Report
about: Report a Sybil attacker of Sturdy
title: Sybil Attacker Report
labels: Sybil Report
assignees: 'skyone'

---

# Related Addresses

```
0x0fe805304e49e993b2c59287000a2726330d2055
0x75d25dfffff585b83b3f535b6ecad842fae3edd2
0x4e3e782053e560fdebd2be4a6c9a1f26c9a0faa4
```

# Reasoning

These three addresses have many internal ETH transfers, back and forth, and the amounts are relatively small

such as  

https://etherscan.io/tx/0x07c22b36e66c7f35f94201900a5ffcc14d717d3b79547f39dba99343623f1fae 0x75-->0x0f 0.007E

https://etherscan.io/tx/0x17a6484a188aa743b371ac7d2126c4012456c6612e6a3cef37d9cf201093c75e 0x0f-->0x75 0.01E

https://etherscan.io/tx/0x1aac5b0ed1569412405c609462956d95620c2a0f248494a462a70eb13d7961a8 0x75-->0x4e 0.01E

https://etherscan.io/tx/0x56ac3f2036a5ac1cfed84a16110805a90b188ae1c9ff584fc8b8b6c6e4fd4456 0x0x-->0x4e 0.004E

https://etherscan.io/tx/0x6729bc12b3757a2ef3726d4c70bc690c14647bb380e5e5116b97e41daa2f8e7f 0x4e-->0x75 0.02E

# Methodology

I just gave a few examples of txs, but there are many more. Due to the following reasons:

1. Internal transfers, back and forth
2. Very small amounts, all less than 0.1 ETH

it is very suspicious.

# Rewards Address

0x8a09fb23e1c8d0ff9c9fef0bcfc9b9e07b1f0667

**Comment by sforman2000** [comment] 2023-01-08 05:31
Duplicate of https://github.com/sturdyfi/sturdy-airdrop-sybil/issues/1

**Closed as completed by sforman2000** 2023-01-08 05:31 UTC
