### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by skyonedot** [sturdyfi/sturdy-airdrop-sybil#12] opened 2023-01-07 00:33 UTC
---
name: Sybil Attacker Report
about: Report a Sybil attacker of Sturdy
title: Sybil Attacker Report
labels: Sybil Report
assignees: 'skyone'

---

# Related Addresses

```
0x4fecce1be339db44a4fd36f2fef18c6401ac2f8b
0xbda0020b6e44db02ca73e65819ad33eea4a2111c
0x24621aa4dde07f04c57146d83468969010b7489e
```

# Reasoning

These addresses have many internal ETH transfers, back and forth, and the amounts are relatively small

such as  

https://etherscan.io/tx/0x45d185aee338b05d932e149482162708bebe7fe06511e1e27fe13dfbdaecb0b4 0xbd-->0x4f 0.03E

https://etherscan.io/tx/0x9dd4e9481d4dd8474d67d1426cfa760ca9b0701a0ecf36cbb1b199e0c569b8b5 0x4f-->0xbd 0.03E

https://etherscan.io/tx/0x6038e8e3ed8f2a8fd6f246565a594352c1c4f6d6544cf23b0043314cb2fd8325 0x24-->0xbd 0.01E

https://etherscan.io/tx/0xeb6b3ce5da6fdf348a1192d9d345c6f24e93861118d82a38af3c7de002ef694c 0x4f-->0x24 0.025E

https://etherscan.io/tx/0x0b66f250a6983a7fd0da08da6a1a20813ec358c1a40c44cf50f2d75da00af903 0x24-->0x4f 0.025E

# Methodology

I just gave a few examples of txs, but there are many more. Due to the following reasons:

1. Internal transfers, back and forth
2. Very small amounts, all less than 0.1 ETH

it is very suspicious.

# Rewards Address

0x8a09fb23e1c8d0ff9c9fef0bcfc9b9e07b1f0667

**Comment by sforman2000** [comment] 2023-01-08 05:33
Duplicate of https://github.com/sturdyfi/sturdy-airdrop-sybil/issues/4

**Closed as completed by sforman2000** 2023-01-08 05:33 UTC
