### ISSUE TITLE
Sybil Attacker Report

### ISSUE THREAD

**Issue by skyonedot** [sturdyfi/sturdy-airdrop-sybil#9] opened 2023-01-07 00:24 UTC
---
name: Sybil Attacker Report
about: Report a Sybil attacker of Sturdy
title: Sybil Attacker Report
labels: Sybil Report
assignees: 'skyone'

---

# Related Addresses

```
0x7553fa99ab1f429551eec660708c08e14e30584f
0xc79a1415847ed193b64d400c94a220bfb33d0e73
```

# Reasoning

These three addresses have many internal ETH transfers, back and forth, and the amounts are relatively small

such as  

https://etherscan.io/tx/0x1db645a422300b29c3e09fc8ddb94c7bf686abea379102ac1e6ec987f091cc5f 0xc7-->0x75 0.01E

https://etherscan.io/tx/0x586def818e254bd1ce31d496854af9e718f6da3cb78dce9691a6ae14e745ff26 0x75-->0xc7 0.1E

# Methodology

I just gave a few examples of txs, but there are many more. Due to the following reasons:

1. Internal transfers, back and forth
2. Very small amounts, all less than 0.1 ETH

it is very suspicious.

# Rewards Address

0x8a09fb23e1c8d0ff9c9fef0bcfc9b9e07b1f0667

**Comment by sforman2000** [comment] 2023-01-08 05:32
Duplicate of https://github.com/sturdyfi/sturdy-airdrop-sybil/issues/3

**Closed as completed by sforman2000** 2023-01-08 05:32 UTC
